
export default {
    BALANCE_INCREMENT: "bank/BALANCE_INCREMENT",
    BALANCE_DECREMENT: "bank/BALANCE_DECREMENT",
    BANK_INIT_USER: "bank/BANK_INIT_USER",
    USER_LOYALTY_PROGRAMM: 'bank/USER_LOYALTY_PROGRAMM'
  };
  